import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig(({ command }) => ({
  plugins: [react()],
  // Catalyst Web Client Hosting serves the bundle under /app/, so built asset URLs must
  // carry that prefix. Without it index.html requests /assets/... at the origin root,
  // which 404s and leaves a blank page with no console error - the script simply never
  // loads. Dev keeps '/' so the vite server and its proxy work unchanged.
  base: command === 'build' ? '/app/' : '/',
  build: {
    rollupOptions: {
      output: {
        // .mjs ASSETS MUST BE EMITTED AS .js, OR THEY DO NOT LOAD AT ALL.
        //
        // Catalyst Web Client Hosting serves .js as application/javascript and .mjs as
        // application/octet-stream, and a browser refuses to execute an ES module served with
        // a non-JavaScript MIME type. pdf.js ships its worker as pdf.worker.mjs, so the built
        // page 200s on the worker and then dies with "Failed to fetch dynamically imported
        // module" -- a failure that looks like a missing file and is actually a content type.
        //
        // Renaming the emitted asset is enough: the content is identical and every reference
        // to it is generated by the bundler, so nothing needs to be kept in step by hand.
        assetFileNames: (info) => {
          const name = info.names?.[0] || info.name || '';
          if (name.endsWith('.mjs')) return 'assets/[name]-[hash].js';
          return 'assets/[name]-[hash][extname]';
        },
      },
    },
  },
  server: {
    port: 5173,
    proxy: {
      // dev: proxy API calls to the local mock backend
      '/api': { target: process.env.VITE_API_BASE || 'http://localhost:9000', changeOrigin: true, rewrite: (p) => p.replace(/^\/api/, '') },
    },
  },
}));
